from enum import Enum

class ResponseSignal(Enum):

    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_SIZE_EXCEEDS_MAX_SIZE = "FILE_SIZE_EXCEEDS_MAX_SIZE"
    FILE_IS_VALID = "FILE_IS_VALID"
    FILE_UPLOADED_SUCCESSFULLY = "FILE_UPLOADED_SUCCESSFULLY"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_PROCESSING_FAILED = "PROCESSING_FAILED"
    FILE_PROCESSING_sUCCESSFUL = "PROCESSING_SUCCESSFUL"